In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv("RF_datasets/finishedData.csv")

In [3]:
dataset.head()

Unnamed: 0  Opioid Deaths     FIP  unemployment rate  MME per cap  \
0  Autauga County, AL       4.143150  1001.0                5.1       1084.0   
1  Baldwin County, AL      15.578400  1003.0                5.3       1148.5   
2  Barbour County, AL       1.936425  1005.0                8.3        577.6   
3     Bibb County, AL       1.693200  1007.0                6.4        563.0   
4   Blount County, AL       4.313775  1009.0                5.4        459.0   

   % with bachelors  
0              25.0  
1              30.7  
2              12.0  
3              13.2  
4              13.1

In [4]:
X = dataset.iloc[:, 3:].values
y = dataset.iloc[:, 1].values

In [5]:
print(X)

[[   5.1 1084.    25. ]
 [   5.3 1148.5   30.7]
 [   8.3  577.6   12. ]
 ...
 [   5.8 1067.8   17.4]
 [   4.8 1444.    21. ]
 [   5.   566.9   19.8]]


In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [7]:
#from sklearn.preprocessing import StandardScaler

#sc = StandardScaler()
#X_train = sc.fit_transform(X_train)
#X_test = sc.transform(X_test)

In [8]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators=20, random_state=0)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

In [9]:
from sklearn import metrics

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 14.986720763499164
Mean Squared Error: 1571.8607112257591
Root Mean Squared Error: 39.64669861698145


In [10]:
print(y_train[0:10])
print(X_train[0:10])

[ 2.986074  1.077015 10.517985  1.131328  0.593464  6.34868   2.454456
  0.186456  4.717168  1.715714]
[[   4.8 1463.8   12.9]
 [   4.9  967.6   23.7]
 [   4.1  766.6   28.3]
 [   7.9 1229.7   17.2]
 [   4.2  424.7   20.6]
 [   5.   377.5   18.9]
 [   4.9  571.1   19.8]
 [   3.2 1559.5   20.1]
 [   6.3  515.4    9.9]
 [   7.   735.9    8.5]]
