In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv('petrol_consumption.csv')

In [4]:
dataset.head()

Petrol_tax  Average_income  Paved_Highways  Population_Driver_licence(%)  \
0         9.0            3571            1976                         0.525   
1         9.0            4092            1250                         0.572   
2         9.0            3865            1586                         0.580   
3         7.5            4870            2351                         0.529   
4         8.0            4399             431                         0.544   

   Petrol_Consumption  
0                 541  
1                 524  
2                 561  
3                 414  
4                 410

In [19]:
X = dataset.iloc[:, 1:4].values
y = dataset.iloc[:, 4].values
z = dataset.iloc[:, 0].values
print(z)

[ 9.    9.    9.    7.5   8.   10.    8.    8.    8.    7.    8.    7.5
  7.    7.    7.    7.    7.    7.    7.    8.5   7.    8.    9.    9.
  8.5   9.    8.    7.5   8.    9.    7.    7.    8.    7.5   8.    6.58
  5.    7.    8.5   7.    7.    7.    7.    7.    6.    9.    7.    7.  ]


In [17]:
print(X)

[[3.5710e+03 1.9760e+03 5.2500e-01]
 [4.0920e+03 1.2500e+03 5.7200e-01]
 [3.8650e+03 1.5860e+03 5.8000e-01]
 [4.8700e+03 2.3510e+03 5.2900e-01]
 [4.3990e+03 4.3100e+02 5.4400e-01]
 [5.3420e+03 1.3330e+03 5.7100e-01]
 [5.3190e+03 1.1868e+04 4.5100e-01]
 [5.1260e+03 2.1380e+03 5.5300e-01]
 [4.4470e+03 8.5770e+03 5.2900e-01]
 [4.5120e+03 8.5070e+03 5.5200e-01]
 [4.3910e+03 5.9390e+03 5.3000e-01]
 [5.1260e+03 1.4186e+04 5.2500e-01]
 [4.8170e+03 6.9300e+03 5.7400e-01]
 [4.2070e+03 6.5800e+03 5.4500e-01]
 [4.3320e+03 8.1590e+03 6.0800e-01]
 [4.3180e+03 1.0340e+04 5.8600e-01]
 [4.2060e+03 8.5080e+03 5.7200e-01]
 [3.7180e+03 4.7250e+03 5.4000e-01]
 [4.7160e+03 5.9150e+03 7.2400e-01]
 [4.3410e+03 6.0100e+03 6.7700e-01]
 [4.5930e+03 7.8340e+03 6.6300e-01]
 [4.9830e+03 6.0200e+02 6.0200e-01]
 [4.8970e+03 2.4490e+03 5.1100e-01]
 [4.2580e+03 4.6860e+03 5.1700e-01]
 [4.5740e+03 2.6190e+03 5.5100e-01]
 [3.7210e+03 4.7460e+03 5.4400e-01]
 [3.4480e+03 5.3990e+03 5.4800e-01]
 [3.8460e+03 9.0610e+03 5.79

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [8]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators=20, random_state=0)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

In [10]:
from sklearn import metrics

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 51.76500000000001
Mean Squared Error: 4216.166749999999
Root Mean Squared Error: 64.93201637097064


In [11]:
print(y_pred)

[574.1  514.6  604.8  589.75 625.55 592.5  594.9  573.3  468.55 536.8 ]


In [12]:
print(y_test)

[534 410 577 571 577 704 487 587 467 580]


In [13]:
dataset.columns

Index(['Petrol_tax', 'Average_income', 'Paved_Highways',
       'Population_Driver_licence(%)', 'Petrol_Consumption'],
      dtype='object')

In [14]:
len(dataset.columns)

5

In [15]:
print(X_train)

[[-1.32525691e-01  1.50577399e+00  2.25854636e+00 -9.15791057e-01]
 [-6.28192647e-01 -1.83367022e+00  2.12333843e-01 -1.12852703e+00]
 [-1.32525691e-01 -1.78897047e+00 -4.54194551e-01 -5.25775100e-01]
 [-1.32525691e-01 -8.78212954e-01  8.77245103e-01  4.15208375e-02]
 [-6.28192647e-01  1.27482526e+00  1.07480487e+00  2.89712810e-01]
 [ 1.35447518e+00 -8.42825648e-01 -1.13743332e+00  5.92488356e-02]
 [-6.28192647e-01 -4.00925436e-02 -4.64436395e-01  8.21552752e-01]
 [-6.28192647e-01  7.42153173e-01  2.93282707e-02  2.61208055e+00]
 [-6.28192647e-01  8.82232011e-04  1.22196399e+00  1.65616824e-01]
 [ 3.63141265e-01 -2.41241442e-01  4.54996025e-02 -2.42127131e-01]
 [ 1.35447518e+00  1.07926383e+00 -9.04835665e-01 -1.16398303e+00]
 [-6.28192647e-01 -2.07716626e-01  7.28199328e-01 -8.25751488e-02]
 [-6.28192647e-01 -1.23208602e+00 -4.90849570e-01 -2.42127131e-01]
 [-6.28192647e-01  5.13066928e-01  5.46541367e-01  1.53067267e+00]
 [-6.28192647e-01 -3.26425844e-02 -5.85182339e-01  4.66992791e